dj4e/autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/2.1/topics/http/urls/
app_name='autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
]

# Note that make_ and auto_ give us uniqueness within this application

dj4e/dj4e/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    path('autos/', include('autos.urls')),                   # Add
]

dj4e/home/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name='home'
urlpatterns = [
    path('', TemplateView.as_view(template_name='home/hello.html'), name='home'),
]

dj4e/autos/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Make(models.Model):
    name = models.CharField(
            max_length=200,
            help_text='Enter a make (e.g. Dodge)',
            validators=[MinLengthValidator(2, "Make must be greater than 1 character")]
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Auto(models.Model) :
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)

    # Shows up in the admin list
    def __str__(self):
        return self.nickname

dj4e/home/models.py
from django.db import models

# Create your models here.

dj4e/autos/forms.py
from django.forms import ModelForm
from autos.models import Make

# Create the form class.
class MakeForm(ModelForm):
    class Meta:
        model = Make
        fields = '__all__'

dj4e/autos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.template.loader import render_to_string

from autos.models import Auto, Make
from autos.forms import MakeForm

# Create your views here.

class MainView(LoginRequiredMixin, View) :
    def get(self, request):
        mc = Make.objects.all().count();
        al = Auto.objects.all();

        ctx = { 'make_count': mc, 'auto_list': al };
        return render(request, 'autos/auto_list.html', ctx)

class MakeView(LoginRequiredMixin,View) :
    def get(self, request):
        ml = Make.objects.all();
        ctx = { 'make_list': ml };
        return render(request, 'autos/make_list.html', ctx)

class MakeCreate(LoginRequiredMixin,CreateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('make:all')

class MakeUpdate(LoginRequiredMixin, UpdateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('make:all')

class MakeDelete(LoginRequiredMixin, DeleteView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('make:all')

# Take the easy way out on the main table
class AutoCreate(LoginRequiredMixin,CreateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

class AutoUpdate(LoginRequiredMixin, UpdateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

class AutoDelete(LoginRequiredMixin, DeleteView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

# We use reverse_lazy rather than reverse in the constructor attributes below
# because views.py is loaded by urls.py and in urls.py as_view() causes
# the constructor for the view class to run before urls.py has been
# completely loaded and urlpatterns has been processed.

# References

# https://docs.djangoproject.com/en/2.2/ref/class-based-views/generic-editing/#createview

dj4e/home/views.py
from django.shortcuts import render

# Create your views here.

dj4e/autos/templates/autos/auto_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

dj4e/autos/templates/autos/auto_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

dj4e/autos/templates/autos/auto_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Auto List</h1>
  {% if auto_list %}
  <ul>
    {% for auto in auto_list %}
      <li>
          {{ auto.nickname }} ({{ auto.make }})
          (<a href="{% url 'autos:auto_update' auto.id %}">Update</a> |
          <a href="{% url 'autos:auto_delete' auto.id %}">Delete</a>) <br/>
          {{ auto.comments }} ({{ auto.mileage }} miles)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no autos in the library.</p>
  {% endif %}
  <p>
    {% if make_count > 0 %}
      <a href="{% url 'autos:auto_create' %}">Add an auto</a>
    {% else %}
      Please add a make before you add an auto.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'autos:make_list' %}">View makes</a> ({{ make_count }}) |
    <a href="{% url 'autos:make_create' %}">Add a make</a>
  </p>
{% endblock %}

dj4e/autos/templates/autos/make_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the make: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

dj4e/autos/templates/autos/make_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

dj4e/autos/templates/autos/make_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Make List</h1>
  {% if make_list %}
  <ul>
    {% for make in make_list %}
      <li>
          {{ make.name }}
         (<a href="{% url 'autos:make_update' make.id %}">Update</a> |
          <a href="{% url 'autos:make_delete' make.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no makes in the library.</p>
  {% endif %}
  <p><a href="{% url 'autos:make_create' %}">Add a make</a></p>
  <p>
    <a href="{% url 'autos:all' %}">Back to autos</a>
  </p>
{% endblock %}

dj4e/home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
    <!-- Edit samples/settings.py and add APP_NAME = 'DJ4e Samples' or similar -->
    <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<meta name="wa4e" value="42-42">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<script
  src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/2.2.7/webcomponents-loader.js"
  crossorigin="anonymous"></script>

<!--
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/fetch/3.0.0/fetch.js"
  crossorigin="anonymous"></script>
-->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

</head>
<body>
{% block navbar %} {% endblock %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

dj4e/home/templates/home/hello.html
<p1>Hello World</p1>
<meta name="wa4e" content="97e8527feaf77a97fc38f34216141515">
<ul>
<li><a href="/autos">Autos CRUD</a>
<ul>